package com.huangyangwei.iknow.conversation;

import io.micrometer.core.instrument.*; import jakarta.validation.Valid; import jakarta.validation.constraints.*; import java.util.*; import java.util.concurrent.*; import java.util.concurrent.atomic.*; import org.springframework.http.MediaType; import org.springframework.security.core.annotation.AuthenticationPrincipal; import org.springframework.security.core.userdetails.UserDetails; import org.springframework.web.bind.annotation.*; import org.springframework.web.servlet.mvc.method.annotation.SseEmitter;
@RestController @RequestMapping("/api/v1/conversations") public class ConversationController { private final ConversationService service; private final ExecutorService executor; private final Timer firstEvent; public ConversationController(ConversationService s,MeterRegistry meters){service=s;executor=Executors.newVirtualThreadPerTaskExecutor();firstEvent=Timer.builder("rag.first_sse_token.latency").publishPercentileHistogram().register(meters);}
 @PostMapping public Map<String,UUID> create(@AuthenticationPrincipal UserDetails user,@RequestBody @Valid CreateRequest r){return Map.of("id",service.create(user.getUsername(),r.title()));} @GetMapping("/{id}/messages") public List<ConversationService.Message> messages(@AuthenticationPrincipal UserDetails user,@PathVariable UUID id){return service.messages(id,user.getUsername());}
 @PostMapping("/{id}/questions") public ConversationService.Answer ask(@AuthenticationPrincipal UserDetails user,@PathVariable UUID id,@RequestBody @Valid QuestionRequest r){return service.ask(id,user.getUsername(),r.question());}
 @PostMapping(value="/{id}/questions:stream",produces=MediaType.TEXT_EVENT_STREAM_VALUE) public SseEmitter stream(@AuthenticationPrincipal UserDetails user,@PathVariable UUID id,@RequestBody @Valid QuestionRequest r){var emitter=new SseEmitter(30_000L);var terminal=new AtomicBoolean();var task=new AtomicReference<Future<?>>();var lock=new Object();var sample=Timer.start();emitter.onTimeout(()->finishError(emitter,terminal,task,lock,"SSE_TIMEOUT","stream timed out"));task.set(executor.submit(()->{try{if(terminal.get())return;var answer=service.ask(id,user.getUsername(),r.question,terminal::get);synchronized(lock){if(terminal.get())return;emitter.send(SseEmitter.event().name("token").data(Map.of("content",answer.message().content())));sample.stop(firstEvent);emitter.send(SseEmitter.event().name("done").data(answer));terminal.set(true);emitter.complete();}}catch(CancellationException ignored){}catch(Exception e){finishError(emitter,terminal,task,lock,"RAG_ERROR",e.getMessage());}}));return emitter;}
 private void finishError(SseEmitter emitter,AtomicBoolean terminal,AtomicReference<Future<?>> task,Object lock,String code,String message){synchronized(lock){if(!terminal.compareAndSet(false,true))return;var future=task.get();if(future!=null)future.cancel(true);try{emitter.send(SseEmitter.event().name("error").data(Map.of("code",code,"message",message)));}catch(Exception ignored){}emitter.complete();}}
 public record CreateRequest(@Size(max=255) String title){} public record QuestionRequest(@NotBlank @Size(max=4000) String question){}
}
