package com.huangyangwei.iknow.conversation;

import jakarta.validation.Valid; import jakarta.validation.constraints.*; import java.util.*; import java.util.concurrent.*; import org.springframework.http.MediaType; import org.springframework.security.core.annotation.AuthenticationPrincipal; import org.springframework.security.core.userdetails.UserDetails; import org.springframework.web.bind.annotation.*; import org.springframework.web.servlet.mvc.method.annotation.SseEmitter;
@RestController @RequestMapping("/api/v1/conversations") public class ConversationController { private final ConversationService service; private final Executor executor; public ConversationController(ConversationService s){service=s;executor=Executors.newVirtualThreadPerTaskExecutor();}
 @PostMapping public Map<String,UUID> create(@AuthenticationPrincipal UserDetails user,@RequestBody @Valid CreateRequest r){return Map.of("id",service.create(user.getUsername(),r.title()));} @GetMapping("/{id}/messages") public List<ConversationService.Message> messages(@AuthenticationPrincipal UserDetails user,@PathVariable UUID id){return service.messages(id,user.getUsername());}
 @PostMapping("/{id}/questions") public ConversationService.Answer ask(@AuthenticationPrincipal UserDetails user,@PathVariable UUID id,@RequestBody @Valid QuestionRequest r){return service.ask(id,user.getUsername(),r.question());}
 @PostMapping(value="/{id}/questions:stream",produces=MediaType.TEXT_EVENT_STREAM_VALUE) public SseEmitter stream(@AuthenticationPrincipal UserDetails user,@PathVariable UUID id,@RequestBody @Valid QuestionRequest r){var emitter=new SseEmitter(30_000L); executor.execute(()->{try{var answer=service.ask(id,user.getUsername(),r.question()); emitter.send(SseEmitter.event().name("token").data(Map.of("content",answer.message().content())));emitter.send(SseEmitter.event().name("done").data(answer));emitter.complete();}catch(Exception e){try{emitter.send(SseEmitter.event().name("error").data(Map.of("code","RAG_ERROR","message",e.getMessage())));}catch(Exception ignored){}emitter.complete();}});return emitter;}
 public record CreateRequest(@Size(max=255) String title){} public record QuestionRequest(@NotBlank @Size(max=4000) String question){}
}
