package com.huangyangwei.iknow.conversation;

import com.fasterxml.jackson.core.JsonProcessingException; import com.fasterxml.jackson.databind.ObjectMapper; import com.huangyangwei.iknow.rag.*; import io.micrometer.core.instrument.*; import java.time.Instant; import java.util.*; import java.util.function.BooleanSupplier; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service public class ConversationService {
 private final ModelAdapter model; private final PublishedKnowledgeService knowledge; private final JdbcTemplate jdbc; private final ObjectMapper json; private final Timer firstToken;
 public ConversationService(ModelAdapter model,PublishedKnowledgeService knowledge,JdbcTemplate jdbc,ObjectMapper json,MeterRegistry meters){this.model=model;this.knowledge=knowledge;this.jdbc=jdbc;this.json=json;firstToken=Timer.builder("rag.first_token.latency").publishPercentileHistogram().register(meters);}
 @Transactional public UUID create(String owner,String title){var userId=ensureUser(owner);var id=UUID.randomUUID();jdbc.update("insert into conversation(id,user_id,title,created_at) values(?,?,?,?)",id,userId,title,Instant.now());return id;}
 public List<Message> messages(UUID id,String owner){authorize(id,owner);return jdbc.query("select id,role,content,evidence_snapshot,confidence,created_at from conversation_message where conversation_id=? order by created_at",(rs,row)->new Message(rs.getObject(1,UUID.class),rs.getString(2),rs.getString(3),rs.getObject(5,Double.class),readEvidence(rs.getString(4)),rs.getTimestamp(6).toInstant()),id);}
 @Transactional public Answer ask(UUID id,String owner,String question){return ask(id,owner,question,()->false);}
 @Transactional public Answer ask(UUID id,String owner,String question,BooleanSupplier cancelled){checkCancelled(cancelled);authorize(id,owner);var evidence=knowledge.findEvidence(question);checkCancelled(cancelled);var generated=firstToken.record(()->model.answer(question,evidence));checkCancelled(cancelled);var now=Instant.now();var userMessageId=UUID.randomUUID();jdbc.update("insert into conversation_message(id,conversation_id,role,content,created_at) values(?,?,?,?,?)",userMessageId,id,"user",question,now);checkCancelled(cancelled);var message=new Message(UUID.randomUUID(),"assistant",generated.text(),generated.confidence(),evidence,Instant.now());jdbc.update("insert into conversation_message(id,conversation_id,role,content,evidence_snapshot,confidence,created_at) values(?,?,?,?,?,?,?)",message.id(),id,message.role(),message.content(),writeEvidence(evidence),message.confidence(),message.createdAt());return new Answer(userMessageId,message);}
 @Transactional public void compensate(Answer answer){jdbc.update("delete from conversation_message where id in (?,?)",answer.userMessageId(),answer.message().id());}
 private void checkCancelled(BooleanSupplier cancelled){if(cancelled.getAsBoolean()||Thread.currentThread().isInterrupted())throw new java.util.concurrent.CancellationException("SSE stream was cancelled");}
 private UUID ensureUser(String username){var ids=jdbc.query("select id from app_user where username=?",(rs,row)->rs.getObject(1,UUID.class),username);if(!ids.isEmpty())return ids.getFirst();var id=UUID.randomUUID();try{jdbc.update("insert into app_user(id,username,password_hash,created_at) values(?,?,?,?)",id,username,"EXTERNAL_AUTH",Instant.now());return id;}catch(org.springframework.dao.DuplicateKeyException ignored){return jdbc.queryForObject("select id from app_user where username=?",UUID.class,username);}}
 private void authorize(UUID conversationId,String owner){var allowed=jdbc.queryForObject("select count(*) from conversation c join app_user u on u.id=c.user_id where c.id=? and u.username=?",Integer.class,conversationId,owner);if(allowed==null||allowed==0)throw new SecurityException("conversation is not owned by current user");}
 private String writeEvidence(List<ModelAdapter.Evidence> e){try{return json.writeValueAsString(e);}catch(JsonProcessingException x){throw new IllegalStateException("cannot serialize evidence",x);}}
 private List<ModelAdapter.Evidence> readEvidence(String value){try{return value==null?List.of():Arrays.asList(json.readValue(value,ModelAdapter.Evidence[].class));}catch(JsonProcessingException x){throw new IllegalStateException("cannot read evidence",x);}}
 public record Message(UUID id,String role,String content,Double confidence,List<ModelAdapter.Evidence> evidence,Instant createdAt){} public record Answer(UUID userMessageId,Message message){}
}
